# This is where you define all the services 
services:
    # try to choose a sluggified name :) 
  - name: "mysql"
    # you can define a path if the path is not $ROOT/${name}
    path: ".devctl/mysql"
    # some description
    description: "5.7"
    # This appears at the end to give some guidance to the user
    notes: "Check .devctl/mysql/.devconfig.yaml for credentials and configuration"
  
    # this one doesn't have a path because it's implicit from the name
  - name: "frontend"
    description: "Powered by create-react-app"
    proxy:
        # This is create-react-app ports
      - port: 3000
        # this defaults to HTTP
        protocol: http
        paths:
          # the proxy uses the Host header to do the routing.
          - localhost
          # If you want to use a domain, make sure it's pointing to 127.0.0.1 in /etc/hosts
          - example.com
    # This appears at the end to give some guidance to the user
    # Extra indentation changes the color of the text :)
    notes: |
      To start the dev server:
          yarn frontend start

  - name: "graphql"
    description: "Powered by Prisma"
    proxy:
      - port: 4466
        paths:
          # When it hits /api, proxies to graphql
          - localhost/graphql
          # Again, if you want to use a domain, make sure it's pointing to 127.0.0.1 in /etc/hosts
          - example.com/graphql
    notes: |
      Run these commands the first time: 
          yarn graphql exec prisma deploy
          yarn graphql exec prisma seed
      GraphQL should be running now!

# This enables the simple reverse-proxy 
proxy:
  enabled: true
  # If SSL keys are provided, this defaults to 443. 
  # If NO SSL Keys are provided, this defaults to 80
  # You can force another port here
  port: 80 

  # These below would enable SSL development. Those certs would have been generated by mkcert and the CA would be trusted
  # We've opted out from automating this because of potential security issues
  # 
  # ssl: 
  #   key: .devctl/ssl/example.com-key.pem
  #   cert: .devctl/ssl/example.com.pem


environment:
  - name: dev
    description: Run services locally