# this builds the docker-compose for this service
compose: 

  # this is the base file. It gets deep-merged by environment. 
  # In this example, there's only 1 environment, but we've separated it so it's clearer 
  default:
    prisma: 
      image: "prismagraphql/prisma:1.33"
      restart: always
      ports:
      - "4466:4466"
      
  dev: 
    prisma: 
      links: 
        - mysql
      environment:
        PRISMA_CONFIG: |
          port: 4466
          databases:
            default:
              connector: mysql
              host: mysql
              user: root
              password: prisma
              rawAccess: true
              port: 3306
              migrations: true`

  # This is an example of how it would look if you had a staging server
  # 
  # staging:
  #   prisma:
  #     extra_hosts:
  #       - mysql:192.168.11.1
  #     environment:
  #       PRISMA_CONFIG: |
  #         port: 4466
  #         databases:
  #           default:
  #             connector: mysql
  #             host: mysql
  #             user: prisma-user
  #             password: prisma-password
  #             rawAccess: true
  #             port: 3306
  #             migrations: true`