# This builds the docker compose
# But since we're not running create-react-app in docker, we can leave it empty
compose: {}

# This builds the .env files when its selected
dotenv: 
  # this is the default. It gets merged thru all environment
  default:
    # Fixes the CRA error with babel-jest
    SKIP_PREFLIGHT_CHECK: true
  # This only gets merged when you select dev. Since we only have 1 environment in this example, it'll always get merged
  dev:
    # Prevent from opening the browser automatically (it's annoying)
    BROWSER: falses